## Estas notas de TensorFlow fueron tomadas en 2022 y actualizadas en Octubre de 2023. Las comparto con el proposito de difundir y resguardar esta información para el uso propio y externo.



In [1]:
import tensorflow as tf

In [2]:
tf.__version__ # Por defecto en Colab se carga esta versión.

'2.13.0'

In [5]:
import numpy as np # es necesario importar numpy para trabajar conjuntamente con TensorFlow

### Constantes

In [6]:
# Definir una constante
tensor = tf.constant([[23, 4], [32, 51]])

In [7]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [8]:
# Obtener el tamaño de un tensor.
tensor.shape

TensorShape([2, 2])

#### Valores de una constante

In [9]:
# Obtener los valores de una constante con numpy.
tensor.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [10]:
# Convertir un array de numpy a un tensor de TensorFlow
numpy_tensor = np.array([[23,  4], [32, 51]])

In [11]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [12]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Variables

In [13]:
tf_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [14]:
# Consultar los valore de una variable
tf_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [15]:
# Cambiar el valor de una variable
tf_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [16]:
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operaciones con tensores

In [17]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Sumar un escalar a un tensor

In [18]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplicar un escalar por un tensor

In [19]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Utilizar funciones de Numpy sobre tensores de TensorFlow

In [20]:
# Obtener los cuadrados de todos los números de un tensor de TensorFlow
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [21]:
# Obtener la raíz cuadrada de todos los números de un tensor de TensorFlow
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Producto escalar entre dos tensores

In [23]:
tensor_2 = tf.constant([[23, 4], [32, 51]])
np.dot(tensor, tensor_2)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Strings

In [24]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

#### Operaciones simples con strings

In [25]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [26]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Almacenar arrays de strings

In [27]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [28]:
# Iterar sobre un array de strings en TF
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
